### ISSUE TITLE
可以实现监听吗？

### ISSUE THREAD

**Issue by yepwait** [ZhangHao555/BannerRecyclerView#10]

**Comment by ZhangHao555** [comment]
要什么监听 你可以自己添加

**Comment by yepwait** [comment]
好的，已经加上了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhangHao555/BannerRecyclerView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 下午3:17
收件人:&nbsp;"ZhangHao555/BannerRecyclerView"<BannerRecyclerView@noreply.github.com&gt;;
抄送:&nbsp;"杨鹏"<1239738103@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangHao555/BannerRecyclerView] 可以实现监听吗？ (#10)





 
要什么监听 你可以自己添加
